/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ttt.james.server;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author New User
 */
public class MainMenu extends javax.swing.JFrame {
    public static TTTWebService ws;
    public int currentID;
    public String currentUsername;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        ws = new TTTWebService();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainmenu_titleLbl = new javax.swing.JLabel();
        mainMenu_currentUsername = new javax.swing.JLabel();
        mainmenu_myHistoryBtn = new javax.swing.JButton();
        mainmenu_leaderboardBtn = new javax.swing.JButton();
        mainmenu_logoutBtn = new javax.swing.JButton();
        mainmenu_newGameBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        openGamesTbl = new javax.swing.JTable();
        mainmenu_openGamesTbl = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        gameToJoin_cb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        joinGame_Btn = new javax.swing.JButton();
        MyGames = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainmenu_titleLbl.setText("Welcome back : ");

        mainmenu_myHistoryBtn.setText("My History");
        mainmenu_myHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_myHistoryBtnActionPerformed(evt);
            }
        });

        mainmenu_leaderboardBtn.setText("Global Leaderboard");
        mainmenu_leaderboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_leaderboardBtnActionPerformed(evt);
            }
        });

        mainmenu_logoutBtn.setText("Logout");
        mainmenu_logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_logoutBtnActionPerformed(evt);
            }
        });

        mainmenu_newGameBtn.setText("New Game");
        mainmenu_newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_newGameBtnActionPerformed(evt);
            }
        });

        openGamesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Game ID", "Username", "Started"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(openGamesTbl);

        mainmenu_openGamesTbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainmenu_openGamesTbl.setText("Open Games");

        refreshBtn.setText("Refresh Table");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose game to join");

        joinGame_Btn.setText("Join Game");
        joinGame_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGame_BtnActionPerformed(evt);
            }
        });

        MyGames.setText("My Games");
        MyGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyGamesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainmenu_myHistoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainmenu_titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(mainmenu_leaderboardBtn))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(mainMenu_currentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MyGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainmenu_newGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainmenu_logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainmenu_openGamesTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameToJoin_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinGame_Btn)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainmenu_myHistoryBtn)
                    .addComponent(mainmenu_leaderboardBtn)
                    .addComponent(mainmenu_titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenu_currentUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainmenu_openGamesTbl)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainmenu_newGameBtn)
                        .addGap(96, 96, 96)
                        .addComponent(MyGames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainmenu_logoutBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameToJoin_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(joinGame_Btn))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainmenu_myHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_myHistoryBtnActionPerformed
        // TODO add your handling code here:
        MyHistory h = new MyHistory();
            h.setCred(currentID, currentUsername);
            h.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_mainmenu_myHistoryBtnActionPerformed

    private void mainmenu_leaderboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_leaderboardBtnActionPerformed
        // TODO add your handling code here:
        new Leaderboard().setVisible(true);
        
    }//GEN-LAST:event_mainmenu_leaderboardBtnActionPerformed

    private void mainmenu_logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_logoutBtnActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_mainmenu_logoutBtnActionPerformed

    private void mainmenu_newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_newGameBtnActionPerformed
        // TODO add your handling code here:
        ws.newGame(currentID);
    }//GEN-LAST:event_mainmenu_newGameBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        initOpenGames();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void joinGame_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGame_BtnActionPerformed
        // TODO add your handling code here:
        String str = gameToJoin_cb.getSelectedItem().toString();
        if(!str.matches("")){
            ws.joinGame(currentID, Integer.parseInt(str));
        }
    }//GEN-LAST:event_joinGame_BtnActionPerformed

    private void MyGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyGamesActionPerformed
        // TODO add your handling code here:
        MyGames m = new MyGames();
            m.setInfo(currentID,currentUsername);
            m.setVisible(true);
    }//GEN-LAST:event_MyGamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setUsername( String _username ){
        currentUsername = _username;
        mainmenu_titleLbl.setText(mainmenu_titleLbl.getText() + " " +_username);
        initOpenGames();
    }
    public void setID ( int _id ){
        currentID = _id;
    }
    private void initOpenGames(){
        
        String res [] = ws.showOpenGames().split("\n");
        if(!res[0].matches("ERROR-NOGAMES")){
            int row = 0;
            //openGamesTbl
            DefaultTableModel dm = (DefaultTableModel)openGamesTbl.getModel();
            while(dm.getRowCount() > 0)
            {
                dm.removeRow(0);
            }
            //dm.addRow(res);
            gameToJoin_cb.removeAllItems();
            for( int i = 0; i < res.length ; i++){
                System.out.println(res[i]);
                String parse [] = res[i].split(",");
                if(!parse[1].matches(currentUsername)){
                    dm.addRow(parse);
                    //openGamesTbl.setValueAt(parse[0],row,0);
                   // openGamesTbl.setValueAt(parse[1],row,1);
                    //openGamesTbl.setValueAt(parse[2],row,2);
                    gameToJoin_cb.addItem(parse[0]);
                }
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MyGames;
    private javax.swing.JComboBox<String> gameToJoin_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinGame_Btn;
    private javax.swing.JLabel mainMenu_currentUsername;
    private javax.swing.JButton mainmenu_leaderboardBtn;
    private javax.swing.JButton mainmenu_logoutBtn;
    private javax.swing.JButton mainmenu_myHistoryBtn;
    private javax.swing.JButton mainmenu_newGameBtn;
    private javax.swing.JLabel mainmenu_openGamesTbl;
    private javax.swing.JLabel mainmenu_titleLbl;
    private javax.swing.JTable openGamesTbl;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
